// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM5-L6j_wPZ2c9QSX5UjUziPq1gafWg6o',
    appId: '1:178136796971:web:413dcf6fbe561101cf3f6e',
    messagingSenderId: '178136796971',
    projectId: 'dbmetrobox',
    authDomain: 'dbmetrobox.firebaseapp.com',
    storageBucket: 'dbmetrobox.firebasestorage.app',
    measurementId: 'G-ZGW1FCJ2T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsAMvLiWlLMc6DWvLiXPpQ3AIHtWo0F0M',
    appId: '1:178136796971:android:c4678a2670b46591cf3f6e',
    messagingSenderId: '178136796971',
    projectId: 'dbmetrobox',
    storageBucket: 'dbmetrobox.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6j5ikzIkGFHnihfcVy-b9NOSFrCRjTdg',
    appId: '1:178136796971:ios:209a2f9223ed8437cf3f6e',
    messagingSenderId: '178136796971',
    projectId: 'dbmetrobox',
    storageBucket: 'dbmetrobox.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6j5ikzIkGFHnihfcVy-b9NOSFrCRjTdg',
    appId: '1:178136796971:ios:209a2f9223ed8437cf3f6e',
    messagingSenderId: '178136796971',
    projectId: 'dbmetrobox',
    storageBucket: 'dbmetrobox.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM5-L6j_wPZ2c9QSX5UjUziPq1gafWg6o',
    appId: '1:178136796971:web:01e5d46797524131cf3f6e',
    messagingSenderId: '178136796971',
    projectId: 'dbmetrobox',
    authDomain: 'dbmetrobox.firebaseapp.com',
    storageBucket: 'dbmetrobox.firebasestorage.app',
    measurementId: 'G-NFXKQ9F8PW',
  );
}
